"""empty message

Revision ID: 167d580b055e
Revises: afb2bc803903
Create Date: 2025-03-06 02:08:17.951235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167d580b055e'
down_revision = 'afb2bc803903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
